name: Build documentation

on:
#  push:
#    branches:
#      - main
#      - v*-release
  # making all actions so they only run manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: chat-ui
      additional_args: --not_python_module
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
